version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
  disable:
    # TODO(ross): fix errors reported by these checkers and enable them
    - dupl # Tool for code clone detection [fast: true, auto-fix: false]
    - gochecknoglobals # Checks that no globals are present in Go code [fast: true, auto-fix: false]
    - gochecknoinits # Checks that no init functions are present in Go code [fast: true, auto-fix: false]
    - goconst # Finds repeated strings that could be replaced by a constant [fast: true, auto-fix: false]
    - lll # Reports long lines [fast: true, auto-fix: false]
    - depguard # Go linter that checks if package imports are in a list of acceptable packages [fast: true, auto-fix: false]
linters-settings:
  goimports:
    local-prefixes: github.com/nspcc-dev/saml
  govet:
    disable:
      - shadow
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

issues:
  exclude-use-default: false
  exclude:
    - G104 # 'Errors unhandled. (gosec)
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: example/
      linters:
        - errcheck
